require(['jquery'],function($){
    $.ajax({
        url:'/api/classify',
        dataType:'json',
        success:function(res){
            console.log(res)
        },
        error:function(error){
            console.warn(error)
        }
    })
})