require.config({
    baseUrl:'/js/',
    paths:{
        'jquery':'./libs/jquery-3.2.1.min',
        'index':'./app/index',
        'render':'./common/render',
        'handlebars':'./libs/handlebars-v4.0.11'
    }
})
require(['index'])